---
title: "Bootstrap"
author: "Rebecca Silva"
date: "7/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
n <- 1e4
B <- 1000
Age <- rep(c(6:80), 2)
Sex <- c(rep("F", 75), rep("M", 75)) 
Sex_NN<- c(rep(0, 75), rep(1, 75)) 
newdata <- data.frame( Age , Sex)
newdata_NN <- data.frame(Age, Sex_NN)
```



###bootstrap GAM sex
```{r}
samplesize

draw <- function(data, testdata, samplesize){
  time_F <- c()
  time_M <- c()
  base_years <- c(27,30, 35)
  place <- 1
  out <- list()
  
  index = sample( seq_len ( nrow ( data ) ), size = samplesize )
  # train and test set
  train = data[ index , ]
 # grp <- sample_n(data, n, replace = T)
  gam_train <- mgcv::gam( Actual_Time ~ s(Age, k = 40) + s(Age, by = as.factor(Sex), k = 60) + Sex, data = train)  #train on sample
  prediction <- predict( gam_train, testdata , type = "response" )
  prediction_data<- cbind( testdata , prediction )
  
  for (i in base_years){
  time_F[place] <- unlist(prediction_data %>%                   #time for female 
    filter(Age == i, Sex == "F") %>% 
    select(prediction))   
  
  time_M[place] <- unlist(prediction_data %>%                  #time for male
    filter(Age == i, Sex == "M") %>% 
    select(prediction)) 
  
  place <- place + 1
}
female <- unlist(prediction_data %>% 
               filter(Sex == "F") %>% 
               select(prediction))
male <- unlist(prediction_data %>% 
               filter(Sex == "M") %>% 
               select(prediction))
#factor27_F = female/time_F[1] #;
#factor27_M = male/time_M[1] 
out$factor30_F = female/time_F[2] ; out$factor30_M = male/time_M[2]
#factor35_F = female/time_F[3] ; factor30_F = male/time_F[3]
return(out) #if was to return all -make it a list 
}

factor27_M_Boot<- do(10)*draw(ds, newdata, samplesize)
factor27_M_mean <- colMeans(factor27_M_Boot)
factor27_F_Boot <- do(10)*draw(ds)
factor27_F_mean <- colMeans(factor27_F_Boot)

##########

factor30_gam <- do(10)*draw(ds, newdata, samplesize) # list but untidy 
factor30_gam <- lapply(factor30_gam, function(x){  #make list of dataframes each with 75 rows and B cols 
  as.data.frame(sapply(x,rbind))
  })

############


F27_CI <- apply(as.matrix(factor27_F_Boot), 2, function(x){
  mean(x)+c(-1.96,1.96)*sd(x)/sqrt(length(x))})

t2 <- as.vector(head(factor27_F_Boot,1))
```

70% train 30% test in each bootstrap (dont need )

###NN_Sex bootstrap 
```{r}
#ds_NN_shuffled<-scaled[sample(nrow(scaled)),]
samplesize = 0.70 * nrow(ds_NN)
set.seed(13)
#shuffled<-scaled[sample(nrow(scaled)),]

#scale new data 
max = apply(newdata_NN, 2, max)
min = apply(newdata_NN, 2, min)
scaled_newdata <- scale(newdata_NN, center = min, scale = max- min)
#scaled_sex <- scaled %>% select(Sex_NN, Age, Actual_Time)

#boot_NN <- function(scaled_data, samplesize){
 index = sample( seq_len ( nrow ( scaled ) ), size = samplesize )
  # train and test set
  trainNN = scaled[index , ]
  #testNN = scaled[-index , ]
  NN_sex = neuralnet(Actual_Time ~ Age + Sex_NN , trainNN, hidden = 2 , linear.output = T, stepmax = 1e7 )
  predict_testNN = predict(NN_sex, scaled_newdata)
  predict_rescale = (predict_testNN * (max(ds_NN$Actual_Time) - min(ds_NN$Actual_Time)))  + min(ds_NN$Actual_Time) #rescale predicted times--- idk if its questionable that i use ds_NN but thats how it was originally scaled 
  prediction_data <- cbind(newdata_NN, predict_rescale)


  index <- 1
  time_F_NN <- c()
  time_M_NN <- c()
for (age in base_years){
  time_F_NN[index] <- unlist(prediction_data %>%                   #time for female 
    filter(Age == age, Sex_NN == 0) %>% 
    select(predict_rescale)) 
 # print(index); print(age)
  
 time_M_NN[index] <- unlist(prediction_data %>%                  #time for male    filter(Age == age, Sex_NN == 1) %>% 
    select(predict_rescale)) 
  
  index <- index + 1
}
femaleNN <- unlist(prediction_data %>% 
               filter(Sex_NN == 0) %>% 
               select(predict_rescale))
maleNN <- unlist(prediction_data %>% 
               filter(Sex_NN == 1) %>% 
               select(predict_rescale))
factor27_F_NN = femaleNN/time_F_NN[1] #;
factor27_M_NN = maleNN/time_M_NN[1] 
#factor30_F = female/time_F[2] ; factor30_M = male/time_M[2]
#factor35_F = female/time_F[3] ; factor30_F = male/time_F[3]
#return(factor27_F_NN) #if was to return all -make it a list 
#}


factor27_F_BootNN <- do(1)*boot_NN(scaled_sex)
F27_CI <- apply(as.matrix(factor27_F_BootNN), 2, function(x){
  mean(x)+c(-1.96,1.96)*sd(x)/sqrt(length(x))})
```

```{r}
t <- as.vector(factor27_F_NN)

pl<-as.data.frame(cbind( Age, t))
p3 <- ggplot(pl, aes(Age, t), na.rm = T)
p3 + geom_point() +geom_line()

pl2<-as.data.frame(cbind( Age, t2))
p4 <- ggplot(pl2, aes(Age, t2))
p4 + geom_point() +geom_line()

t2<- unname(t2)
t2<- t(t2)

t3 <- as.vector(t(as.vector(factor27_M_mean)))

pl3<-as.data.frame(cbind( Age75, t3))
p5 <- ggplot(pl3, aes(Age75, t3), na.rm = T)
p5 + geom_point() +geom_line()

Age75 <- c(6:80)
p3 + geom_point() +geom_line()

t4 <- as.vector(t(as.vector(factor27_F_mean)))
pl4<-as.data.frame(cbind( Age75, t4))
p6 <- ggplot(pl4, aes(Age75, t4))
p6 + geom_point() +geom_line()

ggplot() + geom_point( data = pl4, aes(Age75, t4), color = "blue") +
  geom_point( data = pl3, aes(Age75, t3), color = "red") +
  geom_point( data = pl, aes(Age, t), color = "black")
# 1. change gam bootstrap to taking a data set of 70% instead of only a subset - check plot
# 2. compare factors on same graph
- #see if issue for males too 
# 3. add CIs?  to plot - NO
# 4. get all factors - see if similar bad pattern for GAM model
# 5. make sure stats is good for models TM
# 6. get all factors
# 7. get factors for sex and section model 
# 8. compare factors for runner vs invitational 
# LaTex a solution
```



```{r}
#for each list i will want to do this for each dataframe in each list 
#x in the case is a dataframe 
#so would want another sapply(list, function(x) {
#... all below
#})
sapply(x, function(x) c( "Stand dev" = sd(x), 
                         "Mean"= mean(x),
                         "UpperCI" = mean(x) + 1.96*sd(x),
                         "LowerCI" = mean(x) - 1.96*sd(x),
                         "Median" = median(x)
                       #  "CoeffofVariation" = sd(x)/mean(x,na.rm=TRUE),
                       #  "Minimum" = min(x),
                       #  "Maximun" = max(x),
                        # "Upper Quantile" = quantile(x,1), want: upperCI
                        # "LowerQuartile" = quantile(x,0)  other: lowerCI
                    )
)
```







