---
title: "Model Fitting"
author: "Rebecca Silva"
date: "June 27, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library('splines')
#library('gam')
library(mosaic)
library("mgcv")

```

```{r}
mod1 <- lm(Actual_Time ~ ns(Age), data = ds)
msummary(mod1)


mod2 <- gam(Actual_Time ~ s(Age), data = ds)
summary(mod2)
plot.gam(mod2, se = T)

plot(fitted(mod2),residuals(mod2))
```

###with sex (and section?)
```{r}
mod3 <- gam(Actual_Time ~ s(Age) + Sex + Section, data = ds)
summary(mod3)
plot.gam(mod3, se = T)

plot(fitted(mod3),residuals(mod3))

x_new <- seq(0, max(x), length.out = 100)
y_pred <- predict(gam_y, data.frame(x = x_new))

gam.check(mod3) #residuals

```


###as interaction
```{r}
mod4 <- mgcv::gam(Actual_Time ~ s(Age) + s(Age, by = as.factor(Sex), k = 20) + Sex, data = ds) 
summary(mod4)
plot(mod4, se = T)
mgcv::gam.check(mod4)

plot(fitted(mod4),residuals(mod4))
AIC(mod4) #huge


x_new <- seq(0, max(x), length.out = 100)
y_pred <- predict(gam_y, data.frame(x = x_new))

gam.check(mod4) #residuals
```

```{r}
mod5 <- mgcv::gam(Actual_Time ~ s(Age, by = as.factor(Sex), k= 15) + s(Age, by = as.factor(Section), k = 15), data = ds) 
summary(mod5)  #R= .179 w REML and w/o (AIC a little better w REML)
plot(mod5, se = T) #partial effect plots 
mgcv::gam.check(mod5)
plot(fitted(mod5),residuals(mod5))
AIC(mod5) #huge

#make factor for sex and section together 
ds_new<- ds %>% mutate(Sex_Section = paste(Sex,sep = ".", Section)) 

modSS <- mgcv::gam(Actual_Time ~ s(Age, by = as.factor(Sex_Section), k = 20), data = ds_new) 
summary(modSS)
plot(modSS, se = T)
mgcv::gam.check(modSS_REML)

plot(fitted(modSS),residuals(modSS)) #bad
AIC(modSS)
```
```{r}
modSS_REML <- mgcv::gam(Actual_Time ~ s(Age, by = as.factor(Sex_Section)), data = ds_new, method = "REML") 
summary(modSS_REML)
plot(modSS_REML, se = T)

mod_Test <- mgcv::gam(Actual_Time ~ s(Age, by = as.factor(Sex), k= 15) + Section, data = ds) 
plot(mod_Test, se = T)
summary(mod_Test)
mgcv::gam.check(mod_Test)




```

```{r}
# no intereaction just predictors 
mod_Base <- mgcv::gam(Actual_Time ~ s(Age, k= 30) + as.factor(Section) + as.factor(Sex), data = ds) 
plot(mod_Base, se = T)
summary(mod_Base) # R = .495
mgcv::gam.check(mod_Base)

mod_Sex <- mgcv::gam(Actual_Time ~ s(Age) + s(Age, by = as.factor(Sex), k = 40) + as.factor(Sex), data = ds) 
summary(mod_Sex) #.295
plot(mod_Sex, se = T)
mgcv::gam.check(mod_Sex)

mod_Section <- mgcv::gam(Actual_Time ~ s(Age) + s(Age, by = as.factor(Section), k= 20) + as.factor(Section), data = ds) 
plot(mod_Section, se = T)
summary(mod_Section) #.432
mgcv::gam.check(mod_Section) 

mod_SS <- mgcv::gam(Actual_Time ~ s(Age, k= 30) + Sex_Section, data = ds_new) 
plot(mod_SS, se = T)
summary(mod_SS) #.496
mgcv::gam.check(mod_SS)

mod_SS_inter <- mgcv::gam(Actual_Time ~ s(Age, k= 20) + Sex_Section + s(Age, k = 40, by = as.factor(Sex_Section)) , data = ds_new)  #.506

mgcv::gam.check(mod_SS_inter)

anova(mod_SS, mod_SS_inter, test = "F")

```

##Choosen model: "GAM" : for sex and section
```{r}
#wanted to keep Sex and Section sep. even though Sex_Section does a little better (.506)
set.seed(34)
GAM <- mgcv::gam(Actual_Time ~ s(Age, k= 40) + Sex + Section + s(Age, k= 60, by = as.factor(Sex)) + s(Age, k= 60, by = as.factor(Section)) , data = ds)  #.503

plot(GAM, se = T)
summary(GAM) 

mgcv::gam.check(GAM)


#test if sex interaction needed with anova
GAM_minus <- mgcv::gam(Actual_Time ~ s(Age, k= 40) + Sex + Section + s(Age, k= 60, by = as.factor(Section)) , data = ds) 

anova(GAM_minus, GAM, test = "F") #yes, needed
```

```{r}
set.seed(35)
gam_sex <- mgcv::gam(Actual_Time ~ s(Age, k = 40) + s(Age, by = as.factor(Sex), k = 60) + Sex, data = ds) 
summary(gam_sex)
plot(gam_sex, se = T)
mgcv::gam.check(gam_sex)


```



