---
title: "Test list"
author: "Rebecca Silva"
date: "7/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
a <- c(1,2,3)
b <- c(5,6,3)
c <- c(4,3,8)
df<- as.data.frame(rbind(a,b,c))
```

```{r}
# generating example data
a <- 1:5
names(a)<- c("2018-01-01", "2018-01-15", "2018-01-19", "2018-01-20",                                                                                                   
             "2018-02-15")
b <- 11:16
names(b)<- c("2018-01-01", "2018-01-19", "2018-01-20", "2018-01-29", 
             "2018-02-12", "2018-02-15")
l <- list(a=a,b=b)

# including dates in list
l$adates <- names(l$a)
l$bdates <- names(l$b)

# creating empty data frame to merge with
df <- data.frame(dates=character())

# merge
df <- merge(df, l[c("a","adates")], by.x="dates", by.y="adates", all=TRUE)
df <- merge(df, l[c("b","bdates")], by.x="dates", by.y="bdates", all=TRUE)
```

```{r}
list <- factor30_gam$factor30_F
list2 <- factor30_gam$factor30_M
matrix<- sapply(list, rbind)
df <- as.data.frame(matrix)
lapply(factor30_gam, function(x){
  as.data.frame(sapply(x,rbind))
})
df2 <- as.data.frame(sapply(list2, rbind))
cmatrix<- sapply(list, cbind)

bind_rows(lapply(list, stack))
```
```{r}
f <- prediction_data %>% filter(Sex_NN == 0) 

time27 <- unlist(f %>% filter(Age == 27) %>% select(predict_rescale))

f/time27
```

