---
title: "NN_BootwTrain"
author: "Rebecca Silva"
date: "7/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(caret)
library(nnet)
library(NeuralNetTools)
library(mosaic)
library(neuralnet)
```

```{r}
# create test data (df of all possible combinations)
Age <- rep(c(6:80), 4)
Sex_NN<- c(rep(0, 150), rep(1, 150))
Section_NN <- c(rep(0, 75), rep(1, 75), rep(0, 75), rep(1, 75)) 
test <- data.frame( Age , Sex_NN, Section_NN)

# scale test data 
max = apply(test, 2, max)  
min = apply(test, 2, min)
test_scaled <- scale(test, center = min, scale = max - min)
```

###Boot Function - gets factors 
```{r}
# for train fn in boot method: 
# need to specify hidden layers and regularization param (for over-fitting)
ctrl <- trainControl(method = "boot", number = 10, returnResamp = "all")
nnetGrid <-  expand.grid(size = seq(from = 1, to = 3, by = 1),
                        decay = seq(from = 0.0, to = 0.3, by = 0.01))

# bootstrap fn 
boot_nnet<- function (data, testdata, test_scaled, orig_data){
  # train() builds model by resampling data 25x and choosing optimal size (layers) and decay (avoid over-fitting)
  model.nn <- train( Actual_Time ~ Age + Section_NN + Sex_NN,
                  data = data,
                  method = "nnet",
                  trControl = ctrl,
                  tuneGrid = nnetGrid,
                  trace = FALSE)
              
  # predict and rescale predictions 
  predictions <- predict( model.nn, test_scaled )
  predictions_rescale = (predictions * (max(orig_data$Actual_Time) - 
                                        min(orig_data$Actual_Time)))+ 
    min(orig_data$Actual_Time)
  # bind rescaled predicted values with all age, sex, and section combinations
  prediction_data <- cbind(test, predictions_rescale)  

  # initialize objects for upcoming loop
  index <- 1
  time_FR_NN <- c(); time_FI_NN <- c()
  time_MR_NN <- c(); time_MI_NN <- c()
   
  # predicted times for females and males 
  female <- prediction_data %>% filter(Sex_NN == 0) 
  male <- prediction_data %>% filter(Sex_NN == 1) 
  
  # finds prediction for ages 27, 30, 35 
  for (age in base_years){ #gets base times (27,30,35)
     time_FR_NN[index] <- unlist(female %>% 
                               filter(Age == age, Section_NN == 0) %>% 
                               select(predictions_rescale))
     time_FI_NN[index] <- unlist(female %>% 
                               filter(Age == age, Section_NN == 1) %>% 
                               select(predictions_rescale))
    time_MR_NN[index] <- unlist(male %>% 
                               filter(Age == age, Section_NN == 0) %>% 
                               select(predictions_rescale))
    time_MI_NN[index] <- unlist(male %>% 
                               filter(Age == age, Section_NN == 1) %>% 
                               select(predictions_rescale))
    
    index <- index + 1
  }
  
# find predictions for each combination 
FR_time <- unlist(female %>% filter(Section_NN == 0) %>% 
               select(predictions_rescale)) # times for females all ages 
FI_time <- unlist(female %>% filter(Section_NN == 1) %>% 
               select(predictions_rescale))
MR_time <- unlist(male %>% filter(Section_NN == 0) %>% 
               select(predictions_rescale))
MI_time <- unlist(male %>% filter(Section_NN == 1) %>% 
               select(predictions_rescale))

# finds factors by dividing predicted times by predicted base times (27, 30, 35) 
out$factor30_FR = FR_time/time_FR_NN[2]#times divided by time at age 30
out$factor30_FI = FI_time/time_FI_NN[2]
out$factor30_MR = MR_time/time_MR_NN[2]
out$factor30_MI = MI_time/time_MI_NN[2] 
#divide by time_F_NN[1] and time_F_NN[3] for age 27 and 35 respectively 
  return( out )
}
```

##Bootstrap and tidy output - 
Issue: Overestimating factors
```{r}
out <- list()
B <- 5 # number of bootstrap samples 

# returns list of 4, each has B columns of vector len 75 (all poss ages)
output30_NN <- do(B)* boot_nnet(data = scaled, 
                           test_scaled = test_scaled, 
                           orig_data = ds_NN) 

# tidy - make each list a dataframe with B cols and 75 rows 
factors30_NN <- lapply(output30_NN, function(x){  
  as.data.frame(sapply(x,rbind))
  })
```


##Summarize the 1,000 /(10) bootstrap factors for each age 
```{r}
factors30_CI<- lapply(factors30_NN, function(x){
  apply(x, 1, function(x){
    c(Mean = mean(x), lb = quantile(x, .025), ub = quantile(x, .975))
    })
})
factors30_CI<- lapply(factors30_CI, function(x){t(x)})


### make 4 dataframes 
df30_FR <- data.frame("Age" = Age75, 
                      "Mean" = factors30_CI$factor30_FR[,1],
                      "lb" = factors30_CI$factor30_FR[,2],
                      "ub" = factors30_CI$factor30_FR[,3])
df30_FI <- data.frame("Age" = Age75, 
                      "Mean" = factors30_CI$factor30_FI[,1],
                      "lb" = factors30_CI$factor30_FI[,2],
                      "ub" = factors30_CI$factor30_FI[,3])
df30_MR <- data.frame("Age" = Age75,
                      "Mean" = factors30_CI$factor30_MR[,1],
                      "lb" = factors30_CI$factor30_MR[,2],
                      "ub" = factors30_CI$factor30_MR[,3])
df30_MI <- data.frame("Age" = Age75,
                      "Mean" = factors30_CI$factor30_MI[,1],
                      "lb" = factors30_CI$factor30_MI[,2],
                      "ub" = factors30_CI$factor30_MI[,3])

```

### Visuals 
```{r}

# plot gives CI and mean of all 4 catergories 
SexSectionNN.plot <- ggplot(aes(x = Age), data = df30_FI) +
  geom_point(data = df30_FR, aes( x = Age, y = Mean, color = "green"), size= 0.05) +
  geom_errorbar(data = df30_FR, aes(ymax = ub, ymin = lb), color = "green") +
  geom_ribbon(data = df30_FR, aes( ymin = lb, ymax = ub), alpha = 0.3) +
  geom_point(data = df30_FI, aes( x = Age, y = Mean, color = "red"), size= 0.05) +
  geom_errorbar(data = df30_FI, aes(ymax = ub, ymin = lb), color = "red") +
  geom_ribbon(data = df30_FI, aes( ymin = lb, ymax = ub), alpha = 0.3) +
  geom_point(data = df30_MI, aes( x = Age, y = Mean, color = "blue"), size= 0.05) +
  geom_errorbar(data = df30_MI, aes(ymax = ub, ymin = lb), color = "blue") +
  geom_ribbon(data = df30_MI, aes( ymin = lb, ymax = ub), alpha = 0.3) +
  geom_point(data = df30_MR, aes( x = Age, y = Mean, color = "black"), size= 0.05) +
  geom_errorbar(data = df30_MR, aes(ymax = ub, ymin = lb), color = "black") +
  geom_ribbon(data = df30_MR, aes( ymin = lb, ymax = ub), alpha = 0.3) + 
  scale_color_manual("", labels=c("Male Runner", "Male Invitational",  "Female Runner", "Female Invitational"), values = c(blue = "blue",red = "red", green = "green", black = "black")) +
  ylab("Factor (Age = 30)") +
  scale_x_continuous(limits = c(6, 80), expand = c(0, 1)) +
  theme(legend.position = 'top', 
        legend.spacing.x = unit(1.0, 'cm'), 
        legend.key.size = unit(.2, "cm"))


```

## Dataframe: Mean, lb, ub, for each age- sex- and section
```{r}
df30_FI <- cbind(df30_FI, "Sex" = rep("Female", nrow(df30_FI)), "Section" = rep("Invitational", nrow(df30_FI)))
df30_MI <- cbind(df30_MI, "Sex" = rep("Male", nrow(df30_MI)), "Section" = rep("Invitational", nrow(df30_MI)))
df30_FR <- cbind(df30_FR, "Sex" = rep("Female", nrow(df30_FR)), "Section" = rep("Runner", nrow(df30_FR)))
df30_MR <- cbind(df30_MR, "Sex" = rep("Male", nrow(df30_MR)), "Section" = rep("Runner", nrow(df30_MR)))

factors30_SexSectiondf <- do.call("rbind", list(df30_FI, df30_MI, df30_FR, df30_MR ))

# if want to output 
write.csv(factors30_SexSectiondf, file = "NN30_SexSection", row.names = F)
```

