---
title: "GamResults"
author: "Rebecca Silva"
date: "7/22/2019"
output: html_document
---

Rmd finds factors using gam model that uses imputs sex, section, and age. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(mgcv)
```

```{r}
# creates test set (all poss combinations- 300 observations)
Age <- rep(c(6:80), 4)
Sex <- c(rep("M", 150), rep("F", 150))
Section<- c(rep("Invitational", 75), 
             rep("Runner", 75), rep("Invitational", 75), rep("Runner", 75)) 
testGAM <- data.frame( Age , Sex, Section)
```

```{r}
# bootstrap fn 
boot_gam<- function (data, testdata, samplesize){
  index = sample( seq_len ( nrow ( data ) ), size = samplesize )
  train = data[index , ]
  #old model-- decided to not use train()
  #model <- train( Actual_Time ~ Age + Section_NN + Sex_NN,
                 # data = train,
                 # method = "gam",
                 # trace = FALSE)
  
  model <- mgcv::gam(Actual_Time ~ s(Age, k= 10) + Sex + Section + 
                 s(Age, k= 10, by = as.factor(Sex)) + 
                 s(Age, k= 10, by = as.factor(Section)) , 
               method  = 'REML' , data = train) 
  # predict
  predictions <- predict( model, testdata )
  
  # bind predicted values with all age, sex, and section combinations
  prediction_data <- cbind(testdata, predictions)  

  # initialize objects for upcoming loop
  index <- 1
  time_FR_NN <- c(); time_FI_NN <- c()
  time_MR_NN <- c(); time_MI_NN <- c()
  
  # predicted times for females and males 
  female <- prediction_data %>% filter(Sex == "F") 
  male <- prediction_data %>% filter(Sex == "M") 
  
  # finds prediction for ages 27, 30, 35 
  for (age in base_years){ 
     time_FR_NN[index] <- unlist(female %>% 
                               filter(Age == age, Section == "Runner") %>% 
                               select(predictions))
     time_FI_NN[index] <- unlist(female %>% 
                               filter(Age == age, Section == "Invitational") %>% 
                               select(predictions))
    time_MR_NN[index] <- unlist(male %>% 
                               filter(Age == age, Section == "Runner") %>% 
                               select(predictions))
    time_MI_NN[index] <- unlist(male %>% 
                               filter(Age == age, Section == "Invitational") %>% 
                               select(predictions))
    
    index <- index + 1
  }
  
  # find predictions for each combination 
  FR_time <- unlist(female %>% filter(Section == "Runner") %>% 
               select(predictions)) # times for females all ages 
  FI_time <- unlist(female %>% filter(Section == "Invitational") %>% 
               select(predictions))
  MR_time <- unlist(male %>% filter(Section == "Runner") %>% 
               select(predictions))
  MI_time <- unlist(male %>% filter(Section == "Invitational") %>% 
               select(predictions))

  # finds factors by dividing predicted times by predicted base times (27, 30, 35)
  out$factor30_FR = FR_time/time_FR_NN[2]#times divided by time at age 30 
  out$factor30_FI = FI_time/time_FI_NN[2]
  out$factor30_MR = MR_time/time_MR_NN[2]
  out$factor30_MI = MI_time/time_MI_NN[2]
  #divide by time_FI_GAM[1] and time_FI_GAM[3] for age 27 and 35 respectively 
  return( out )
}
```

##Bootstrap and tidy output 
```{r}
out <- list()
B <- 10 # number of bootstrap samples 

# returns list of 4, each has B columns of vector len 75 (all poss ages)
output30_GAM <- do(B)* boot_gam(data = ds, 
                        testdata = testGAM, 
                        samplesize = 0.85 * nrow(ds)) 

# tidy - make each list a dataframe with B cols and 75 rows
factors30_GAM <- lapply(output30_GAM, function(x){  
  as.data.frame(sapply(x,rbind))
  })
```


##Summarize the 1,000 /(10) bootstrap factors for each age 
```{r}
factors30_CI_GAM<- lapply(factors30_GAM, function(x){
  apply(x, 1, function(x){
    c(Mean = mean(x), lb = quantile(x, .05), ub = quantile(x, .95))
    })
})
factors30_CI_GAM<- lapply(factors30_CI_GAM, function(x){t(x)})

### make 4 dataframes 
df30_FR_gam <- data.frame("Age" = Age75, 
                      "Mean" = factors30_CI_GAM$factor30_FR[,1],
                      "lb" = factors30_CI_GAM$factor30_FR[,2],
                      "ub" = factors30_CI_GAM$factor30_FR[,3], 
                      "Sex" = "Female", "Section" = "Runner")
df30_FI_gam <- data.frame("Age" = Age75, 
                      "Mean" = factors30_CI_GAM$factor30_FI[,1],
                      "lb" = factors30_CI_GAM$factor30_FI[,2],
                      "ub" = factors30_CI_GAM$factor30_FI[,3],
                      "Sex" = "Female", "Section" = "Invitational")
df30_MR_gam <- data.frame("Age" = Age75,
                      "Mean" = factors30_CI_GAM$factor30_MR[,1],
                      "lb" = factors30_CI_GAM$factor30_MR[,2],
                      "ub" = factors30_CI_GAM$factor30_MR[,3],
                      "Sex" = "Male", "Section" = "Runner")
df30_MI_gam <- data.frame("Age" = Age75,
                      "Mean" = factors30_CI_GAM$factor30_MI[,1],
                      "lb" = factors30_CI_GAM$factor30_MI[,2],
                      "ub" = factors30_CI_GAM$factor30_MI[,3],
                      "Sex" = "Male", "Section" = "Invitational")

```

##Dataframe
```{r}
# df with mean, lb, ub, for each age- sex- and section
factors30_SexSectionGAMdf <- do.call("rbind", list(df30_FI_gam, df30_MI_gam, df30_FR_gam, df30_MR_gam ))
```


### Visuals 

```{r}
# plot gives CI and mean of all 4 catergories 
SexSectionGAM.plot <- ggplot(aes(x = Age), data = df30_FI_gam) +
  geom_point(data = df30_FR_gam, aes( x = Age, y = Mean, color = "green"), size= 0.05) +
  geom_errorbar(data = df30_FR_gam, aes(ymax = ub, ymin = lb), color = "green") +
  geom_ribbon(data = df30_FR_gam, aes( ymin = lb, ymax = ub), alpha = 0.3) +
  geom_point(data = df30_FI_gam, aes( x = Age, y = Mean, color = "red"), size= 0.05) +
  geom_errorbar(data = df30_FI_gam, aes(ymax = ub, ymin = lb), color = "red") +
  geom_ribbon(data = df30_FI_gam, aes( ymin = lb, ymax = ub), alpha = 0.3) +
  geom_point(data = df30_MI_gam, aes( x = Age, y = Mean, color = "blue"), size= 0.05) +
  geom_errorbar(data = df30_MI_gam, aes(ymax = ub, ymin = lb), color = "blue") +
  geom_ribbon(data = df30_MI_gam, aes( ymin = lb, ymax = ub), alpha = 0.3) +
  geom_point(data = df30_MR_gam, aes( x = Age, y = Mean, color = "black"), size= 0.05) +
  geom_errorbar(data = df30_MR_gam, aes(ymax = ub, ymin = lb), color = "black") +
  geom_ribbon(data = df30_MR_gam, aes( ymin = lb, ymax = ub), alpha = 0.3) + 
  scale_color_manual("", 
                     labels=c("Male Runner", "Male Invitational",  "Female Runner", "Female Invitational"),
                     values = c(blue = "blue",red = "red", green = "green", black = "black")) +
  ylab("Factor (Age = 30)")+
  scale_x_continuous(limits = c(6, 80), expand = c(0, 1)) +
  theme(legend.position = 'top', 
        legend.spacing.x = unit(1, 'cm'), 
        legend.key.size = unit(.2, "cm"))


```

