---
title: "Gam Boot Sex only"
author: "Rebecca Silva"
date: "July 30, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Age2 <- rep(c(6:80), 2)
Sex2<- c(rep("F", 75), rep("M", 75))
test2 <- data.frame( "Age" = Age2 , "Sex" = Sex2)

```

###Boot Function - gets factors 
```{r}
# bootstrap fn 
boot_gam_SexOnly<- function (data, testdata, samplesize){
  index = sample( seq_len ( nrow ( data ) ), size = samplesize )
  train = data[index , ]
  #old model-- decided to not use train() bc overfiting 
  #model <- train( Actual_Time ~ Age + Sex_NN,
                 # data = train,
                 # method = "gam",
                 # trace = FALSE,
                 # linout = T) # add linout = T next time
  
  model <- mgcv::gam(Actual_Time ~ s(Age, k= 10) + Sex + s(Age, k= 10, by = as.factor(Sex)), 
               method  = 'REML' , 
               data = train) 
  
  # predict
  predictions <- predict( model, testdata)
  
  # bind rescaled predicted values with all age, sex, and section combinations
  prediction_data <- cbind(testdata, predictions)  

  # initialize objects for upcoming loop
  index <- 1
  base_years <- c(27, 30, 35)
  time_F_GAM <- c()
  time_M_GAM <- c()
  
  # predicted times for females and males
  female <- prediction_data %>% filter(Sex == "F") 
  male <- prediction_data %>% filter(Sex == "M") 
  
  # finds prediction for ages 27, 30, 35 
  for (age in base_years){ #gets base times (27,30,35)
     time_F_GAM[index] <- unlist(female %>% 
                               filter(Age == age) %>% 
                               select(predictions))
     time_M_GAM[index] <- unlist(male %>% 
                               filter(Age == age) %>% 
                               select(predictions))
    index <- index + 1
  }
  
  # find predictions for each combination (both sexes)
  F_time <- unlist(female %>% select(predictions)) 
  M_time <- unlist(male %>% select(predictions))

  # finds factors by dividing predicted times by predicted base times   (27, 30, 35)
  out$factor30_F = F_time/time_F_GAM[2]#times divided by time at age 30 
  out$factor30_M = M_time/time_M_GAM[2]
#divide by time_F_GAM[1] and time_F_GAM[3] for age 27 and 35 respectively

  return( out )
}
```

##Bootstrap and tidy output 
```{r}
out <- list()
B <- 10 # number of bootstrap samples 
output30_GAMsex <- do(B)* boot_gam_SexOnly(data = ds, 
                           testdata = test2, 
                           samplesize = 0.85 * nrow(ds)) 

factors30_GAM_SexOnly <- lapply(output30_GAMsex, function(x){  
  as.data.frame(sapply(x,rbind))
  })
```


##Summarize the 1,000 /(10) bootstrap factors for each age 
```{r}
factors30_CI_GAMSexOnly<- lapply(factors30_GAM_SexOnly, function(x){
  apply(x, 1, function(x){
    c(Mean = mean(x), lb = quantile(x, .025), ub = quantile(x, .975))
    })
})
factors30_CI_GAMSexOnly<- lapply(factors30_CI_GAMSexOnly, 
                              function(x){t(x)})

### make 2 dataframes 
df30_F_gam <- data.frame("Age" = Age75, 
                      "Mean" = unlist(factors30_CI_GAMSexOnly$factor30_F[,1]),
                      "lb" = factors30_CI_GAMSexOnly$factor30_F[,2],
                      "ub" = factors30_CI_GAMSexOnly$factor30_F[,3])
df30_M_gam <- data.frame("Age" = Age75, 
                      "Mean" = factors30_CI_GAMSexOnly$factor30_M[,1],
                      "lb" = factors30_CI_GAMSexOnly$factor30_M[,2],
                      "ub" = factors30_CI_GAMSexOnly$factor30_M[,3])

```


##Visuals
```{r}
SexGAM.plot <- ggplot(aes(x = Age), data = df30_F_gam) +
  geom_point(data = df30_F_gam, 
             aes( x = Age, y = Mean, color = "red"), size= 0.05) +
  geom_errorbar(data = df30_F_gam, 
                aes(ymax = ub, ymin = lb), color = "red") +
  geom_ribbon(data = df30_F_gam, 
              aes( ymin = lb, ymax = ub), alpha = 0.3) +
  geom_point(data = df30_M_gam, 
             aes( x = Age, y = Mean, color = "blue"), size= 0.05) +
  geom_errorbar(data = df30_M_gam, 
                aes(ymax = ub, ymin = lb), color = "blue") +
  geom_ribbon(data = df30_M_gam, 
              aes( ymin = lb, ymax = ub), alpha = 0.3) +
  scale_color_manual("", labels=c("Male", "Female"), 
                     values = c(blue = "blue",red = "red")) +
  ylab("Factor (Age = 30)") +
  scale_x_continuous(limits = c(6, 80), expand = c(0, 1)) +
  theme(legend.position = 'top', 
        legend.spacing.x = unit(1, 'cm'), 
        legend.key.size = unit(.2, "cm"))


```

##Compare Sex and SexSection
```{r}
require(gridExtra)
SexGAM.plot
SexSectionGAM.plot
grid.arrange(SexGAM.plot, SexSectionGAM.plot, ncol = 2)
```


##Dataframe

```{r}
df30_F_gam <- cbind(df30_F_gam, "Sex" = rep("Female", nrow(df30_F_gam)))
df30_M_gam <- cbind(df30_M_gam, "Sex" = rep("Male", nrow(df30_M_gam)))
# bind - df of 150 rows 
factors30_SexGAMdf <- rbind.data.frame(df30_F_gam, df30_M_gam)

# once satified - output through csv 
write.csv(factors30_SexGAMdf, "GAM30_Sex", row.names = F)
write.csv(factors30_SexSectionGAMdf, "GAM30_SexSection", row.names = F)
```

