---
title: "Section vs Sex"
author: "Rebecca Silva"
date: "7/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(caret)
library(nnet)
library(NeuralNetTools)
library(tidyr)
library(ggplot2)
library(mosiac)
library(mgcv)
```

##Sex
```{r}
index = sample( seq_len ( nrow (scaled) ), size = nrow( scaled ) ) 
train = scaled[index , ]
set.seed(23)
model.SexNN <- train( Actual_Time ~ Age + Sex_NN,
                  data = train,
                  method = "nnet",
                  trace = FALSE) 
print(model.SexNN) #best Rsquared = .26, RMSE = .07846
```

##Section
```{r}
index = sample( seq_len ( nrow (scaled) ), size = nrow( scaled ) ) 
train = scaled[index , ]
set.seed(32)
model.SectionNN <- train( Actual_Time ~ Age + Section_NN,
                  data = train,
                  method = "nnet",
                  trace = FALSE) # add linout = T next time 
print(model.SectionNN)  #best RMSE = .06937, Rsquared = .423 (chosen)
```


##GAM
```{r}
index = sample( seq_len ( nrow ( ds_NN) ), size = nrow( ds_NN ) ) 
train = ds_NN[index , ]
train2 = ds[index,]

set.seed(2)
model.SexGAM <- train( Actual_Time ~ Age + Sex_NN,
                  data = train,
                  method = "gam",
                  trace = FALSE) # add linout = T next time 

print(model.SexGAM) #rsquared= .269 rmse = 0.0776

 
 
set.seed(4)
model.SexGAM2 <-train( Actual_Time ~ Age  + Section_NN,
                  data = train,
                  method = "gam",
                  trace = FALSE)

print(model.SexGAM2) #RMSE = 0.065, Rsquare = .4905
  
model.SexGAM3 <-train( Actual_Time ~ Age + Sex + Section,
                  data = train2,
                  method = "gam",
                  trace = FALSE) 
print(model.SexGAM3) #rsquared = .495

```