---
title: "NN_Model"
author: "Rebecca Silva"
date: "7/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(mosaic)
library(neuralnet)
```


## Data Normalization 
```{r}
gf_histogram(~ Age, data = ds) # not normal so will scale by normalization (not standardization)
gf_histogram(~ Actual_Time, data = ds) #not normal 

ds_NN <- ds %>% mutate(Section_NN = ifelse(Section == "Runner", 0, 1), 
                       Sex_NN = ifelse(Sex == "F", 0 , 1)) %>% 
        select(Age, Section_NN, Sex_NN, Actual_Time) # make cat vars binary 

#  scaling data 
max = apply(ds_NN, 2, max)
min = apply(ds_NN, 2, min)
scaled <- as.data.frame(scale(ds_NN, center = min, scale = max - min))
```
## Train and Test 
```{r}
# Random sampling
samplesize = 0.70 * nrow(ds_NN)
set.seed(13)
index = sample( seq_len ( nrow ( ds_NN ) ), size = samplesize )

# train and test set
trainNN = scaled[index , ]
testNN = scaled[-index , ]

# fit neural network
#set.seed(21) - if you want same model everytime
NN <-  neuralnet(Actual_Time ~ Age + Section_NN + Sex_NN , trainNN, hidden = 2 , linear.output = T, stepmax = 1e7, threshold = .01 ) #hidden = 1 faster but larger error 

# plot neural network 
plot(NN)
```

```{r}
## Prediction using neural network

predict_testNN = predict(NN, testNN)
predict_testNN = (predict_testNN * (max(ds_NN$Actual_Time) - min(ds_NN$Actual_Time))) + min(ds_NN$Actual_Time)

x<- ds_NN$Actual_Time[-index ]  #true data for tested

plot(x, predict_testNN, col='blue', pch=16, ylab = "predicted", xlab = "real")

abline(0,1)

# Calculate Root Mean Square Error (RMSE)
RMSE.NN = (sum((x - predict_testNN)^2) / nrow(datatest)) ^ 0.5

# Calculate R-squared
ydi<- x
yi<- predict_testNN
 ym<-mean(x)
R<-1- ((sum((yi-ydi)^2))/(sum((ydi-ym)^2)))
```

## K-fold CV attempt
```{r}
#k-fold
set.seed(123) 

#Randomly shuffle the data
ds_NN_shuffled<-ds_NN[sample(nrow(ds_NN)),]

#Create 10 equally size folds
folds <- cut(seq(1,nrow(ds_NN_shuffled)),breaks=10,labels=FALSE)

#Perform 10 fold cross validation
for(i in 1:10){
    #Segement your data by fold using the which() function 
    testIndexes <- which(folds==i,arr.ind=TRUE)
    testData <- ds_NN_shuffled[testIndexes, ]
    trainData <- ds_NN_shuffled[-testIndexes, ]
    #Use the test and train data partitions however you desire...
}

train.control <- trainControl(method = "cv", number = 10)
# Train the model
NN_k= neuralnet(Actual_Time ~ Age + Section_NN + Sex_NN , train.control, hidden = 2 , linear.output = T, stepmax = 1e7 )

# Summarize the results
print(model)

```

###NN_Sex

```{r}
# Random sampling
samplesize = 0.70 * nrow(ds_NN)
set.seed(13)
index = sample( seq_len ( nrow ( ds_NN ) ), size = samplesize )
# train and test set
trainNN = scaled[index , ]
testNN = scaled[-index , ]

# fit neural network
set.seed(21)
NN_sex = neuralnet(Actual_Time ~ Age + Sex_NN , trainNN, hidden = 1 , linear.output = T, stepmax = 1e7 )

# plot neural network
plot(NN)
```

```{r}
## Prediction using neural network

predict_testNN = predict(NN, testNN)
predict_testNN = (predict_testNN * (max(ds_NN$Actual_Time) - min(ds_NN$Actual_Time))) + min(ds_NN$Actual_Time)

x<- ds_NN$Actual_Time[-index ]  #true data for tested
xdata <- ds_NN[-index, ]
test <- cbind(xdata, predict_testNN)

# plot predicted against true 
plot(x, predict_testNN, col='blue', pch=16, ylab = "predicted rating NN", xlab = "real rating")
abline(0,1)

# Calculate Root Mean Square Error (RMSE)
RMSE.NN = (sum((x - as.vector(predict_testNN))^2) / length(x)) ^ 0.5

#Calculate R-squared 
ydi<- x
yi<- predict_testNN
 ym<-mean(x)
R<-1- ((sum((yi-ydi)^2))/(sum((ydi-ym)^2)))
```

