---
title: "NNet_SexOnly"
author: "Rebecca Silva"
date: "7/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Age2 <- rep(c(6:80), 2)
Sex2_NN<- c(rep(0, 75), rep(1, 75))
test2 <- data.frame( "Age" = Age2 , "Sex_NN" = Sex2_NN)

###scale test data 
max = apply(test2, 2, max)  
min = apply(test2, 2, min)
test2_scaled <- scale(test2, center = min, scale = max - min)
names(test2_scaled) <- c( "Age", "Sex_NN")
```

###Boot Function - gets factors 
```{r}
# bootstrap fn 
boot_nnet_SexOnly<- function (data, testdata, test_scaled, orig_data){
  index = sample( seq_len ( nrow ( data) ), size = nrow( data ) ) 
  train = data[index , ]
  model.nn <- train( Actual_Time ~ Age + Sex_NN,
                  data = train,
                  method = "nnet",
                  trace = FALSE,
                  linout = T) 
  # predict
  predictions <- predict( model.nn, test_scaled )
  predictions_rescale = (predictions * (max(orig_data$Actual_Time) - 
                                        min(orig_data$Actual_Time)))+ 
    min(orig_data$Actual_Time)
 
  # bind rescaled predicted values with all age, sex, and section combinations
  prediction_data <- cbind(testdata, predictions_rescale)  
  
  # initialize objects for upcoming loop
  index <- 1
  base_years <- c(27, 30, 35)
  time_F_NN <- c()
  time_M_NN <- c()
  
  # predicted times for females and males
  female <- prediction_data %>% filter(Sex_NN == 0) 
  male <- prediction_data %>% filter(Sex_NN == 1) 
  
  # finds prediction for ages 27, 30, 35 
  for (age in base_years){ 
     time_F_NN[index] <- unlist(female %>% 
                               filter(Age == age) %>% 
                               select(predictions_rescale))
     time_M_NN[index] <- unlist(male %>% 
                               filter(Age == age) %>% 
                               select(predictions_rescale))
    index <- index + 1
  }
  
  # find predictions for each combination 
  F_time <- unlist(female %>% select(predictions_rescale)) 
  M_time <- unlist(male %>% select(predictions_rescale))

  # finds factors by dividing predicted times by predicted base times (27, 30, 35)
  out$factor30_F = F_time/time_F_NN[2]#times divided by time at age 30 
  out$factor30_M = M_time/time_M_NN[2]
  #divide by time_F_NN[1] and time_F_NN[3] for age 27 and 35 respectively 
  return( out )
}
```

##Bootstrap and tidy output 
```{r}
out <- list()
# returns list of 2, each has B columns of vector len 75 (all poss ages)
times_SexOnly <- do(100)* boot_nnet_SexOnly(data = scaled, 
                           testdata = test2,
                           test_scaled = test2_scaled, 
                           orig_data = ds_NN) 

# tidy - make each list a dataframe with B cols and 75 rows
factors30_NN_SexOnly <- lapply(times_SexOnly, function(x){
  as.data.frame(sapply(x,rbind))
  })
```

##Summarize the 1,000 /(100) bootstrap factors for each age 
```{r}
factors30_CI_SexOnly<- lapply(factors30_NN_SexOnly, function(x){
  apply(x, 1, function(x){
    c(Mean = mean(x), lb = quantile(x, .05), ub = quantile(x, .95))
    })
})
factors30_CI_SexOnly<- lapply(factors30_CI_SexOnly, 
                              function(x){t(x)})

### make 2 dataframes 
df30_F <- data.frame("Age" = Age75, 
                      "Mean" = unlist(factors30_CI_SexOnly$factor30_F[,1]),
                      "lb" = factors30_CI_SexOnly$factor30_F[,2],
                      "ub" = factors30_CI_SexOnly$factor30_F[,3])
df30_M <- data.frame("Age" = Age75, 
                      "Mean" = factors30_CI_SexOnly$factor30_M[,1],
                      "lb" = factors30_CI_SexOnly$factor30_M[,2],
                      "ub" = factors30_CI_SexOnly$factor30_M[,3])

```


##Visuals
```{r}
SexNN.plot <- ggplot(aes(x = Age), data = df30_F) +
  geom_point(data = df30_F, 
             aes( x = Age, y = Mean, color = "red"), size= 0.5) +
  geom_errorbar(data = df30_F, 
                aes(ymax = ub, ymin = lb), color = "red") +
  geom_ribbon(data = df30_F, 
              aes( ymin = lb, ymax = ub), alpha = 0.3) +
  geom_point(data = df30_M, 
             aes( x = Age, y = Mean, color = "blue"), size= 0.5) +
  geom_errorbar(data = df30_M, 
                aes(ymax = ub, ymin = lb), color = "blue") +
  geom_ribbon(data = df30_M, 
              aes( ymin = lb, ymax = ub), alpha = 0.3) +
  scale_color_manual("", labels=c("Male", "Female"), 
                     values = c(blue = "blue",red = "red")) +
  ylab("Factor (Age = 30)") +
  scale_x_continuous(limits = c(6, 80), expand = c(0, 1)) +
  theme(legend.position = 'top', 
        legend.spacing.x = unit(1, 'cm'), 
        legend.key.size = unit(.2, "cm"))


```
##Compare Sex and SexSection
```{r}
require(gridExtra)
SexNN.plot
SexSectionNN.plot
grid.arrange(SexNN.plot, SexSectionNN.plot, ncol = 2)
```

##DATAFRAMES

```{r}
df30_F <- cbind(df30_F, "Sex" = rep("Female", nrow(df30_F)))
df30_M <- cbind(df30_M, "Sex" = rep("Male", nrow(df30_M)))
factors30_Sexdf <- rbind.data.frame(df30_F, df30_M)


write.csv(factors30_Sexdf, file = "NN30_Sex", row.names = F)

```

