---
title: "NN_Boot"
author: "Rebecca Silva"
date: "7/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### 1. NN Sex model: Focus on factor 30 first. 

## 1a. Get CIs for factors 

### 2. NN Sex and Section model: factor 30 

## 2a. compare factors for inv. vs runner

#### 1 ###################################


```{r}
samplesize = 0.70 * nrow(ds_NN)  #ds_NN has added binary sex (Sex_NN)
set.seed(13)


###scale test data 
max = apply(newdata_NN, 2, max)  #newdata_NN has age and binary sex
min = apply(newdata_NN, 2, min)
scaled_newdata <- scale(newdata_NN, center = min, scale = max- min)


boot_NN_sex <- function(scaled_data, samplesize, testdata, ds_NN, rescaled_testdata){
  index = sample( seq_len ( nrow ( scaled_data ) ), size = samplesize )
  trainNN = scaled_data[index , ]
  NN_sex = neuralnet(Actual_Time ~ Age + Sex_NN , 
                     trainNN, hidden = 2 , linear.output = T, stepmax = 1e7 )
  predict_testNN = predict(NN_sex, testdata) 
  predict_rescale = (predict_testNN * (max(ds_NN$Actual_Time) - min(ds_NN$Actual_Time)))
    + min(ds_NN$Actual_Time) #rescale predicted times
  prediction_data <- cbind(rescaled_testdata, predict_rescale)


  index <- 1
  time_F_NN <- c()
  time_M_NN <- c()
  out <- list()
  female <- prediction_data %>% filter(Sex_NN == 0) 
  male <- prediction_data %>% filter(Sex_NN == 1) 
  
  for (age in base_years){
     time_F_NN[index] <- unlist(female %>% 
                               filter(Age == age) %>% 
                               select(predict_rescale)) 
    time_M_NN[index] <- unlist(male %>% 
                              filter(Age == age) %>% 
                              select(predict_rescale)) 
    index <- index + 1
  }
  
female_time <- unlist(female %>% 
               select(predict_rescale)) #times for females all ages 
male_time <- unlist(male %>% 
               select(predict_rescale))

out$factor30_F = female_time/time_F_NN[2] ; out$factor30_M = male_time/time_M_NN[2] #times divided by time at age 30 

return(out) 
}


factor30_NN <- do(1)*boot_NN_sex(scaled_sex, samplesize, testdata = scaled_newdata, rescaled_testdata = newdata_NN)

### convert to tidy
factor30_NN <- lapply(factor30_NN, function(x){  #make list of dataframes each with 75 rows and B cols 
  as.data.frame(sapply(x,rbind))
  })

### find mean, sd, CI 

summary_factor3_NN <- lapply(factor30_NN, function(x){
  sapply(x, function(x) c( "Stand dev" = sd(x), 
                         "Mean"= mean(x),
                         "LowerCI" = mean(x) - 1.96*sd(x),
                         "UpperCI" = mean(x) + 1.96*sd(x),
                         "Median" = median(x))
  )
})
```


### Visuals 
```{r}
f <- as.vector(factor30_NN$factor30_F) ; m <- as.vector(factor30_NN$factor30_M)
df <- as.data.frame(cbind( Age75, f))
dm <- as.data.frame(cbind( Age75, m))
ggplot() + geom_point( data = df, aes(Age75, f), color = "blue") +
  geom_point( data = dm, aes(Age75, m), color = "red")
#interesting because even relative to their own sex, males deteriote and improve at slower speeds (ie older male needs more headstart relative to 30 male than older female relative to 30 yr old female)
```

### 2. NN Sex and Section 


```{r}
samplesize = 0.70 * nrow(ds_NN)  #ds_NN has added binary sex (Sex_NN)
set.seed(13)

### create test data 
AgeSection <- rep(c(6:80), 4)
SexSection<- c(rep(0, 150), rep(1, 150))
Section <- c(rep(0, 75), rep(1, 75), rep(0, 75), rep(1, 75)) 
testdataSection <- data.frame( AgeSection , SexSection, Section)



###scale test data 
max = apply(testdataSection, 2, max)  #newdata_NN has age and binary sex
min = apply(testdataSection, 2, min)
scaled_testdataSection <- scale(testdataSection, center = min, scale = max- min)


boot_NN_Section <- function(scaled_data, samplesize, ds_NN, testdata, rescaled_testdata){
  index = sample( seq_len ( nrow ( scaled_data) ), size = samplesize ) 
  trainNN = scaled_data[index , ]  
  NN_section = neuralnet(Actual_Time ~ Age + Section_NN + Sex_NN, 
                     trainNN, hidden = 2 , linear.output = T, stepmax = 1e7 )
  
 # testagain <- predict(NN, scaled_testdataSection)
  
#  plot(NN); plot(NN_section) #so... depends on number of steps.. maybe need to raise the steps .. or maybe thats why need to bootstap : should look up how to make sure number of steps is larger enough in neural network 
  
  predict_testNN = predict(NN_section, testdata)
  predict_rescale = (predict_testNN * (max(ds_NN$Actual_Time) - min(ds_NN$Actual_Time))) + min(ds_NN$Actual_Time) #rescale predicted times
  prediction_data <- cbind(rescaled_testdata, predict_rescale)  

  index <- 1
  time_FR_NN <- c(); time_FI_NN <- c()
  time_MR_NN <- c(); time_MI_NN <- c()
  out <- list()
  female <- prediction_data %>% filter(SexSection == 0) 
  male <- prediction_data %>% filter(SexSection == 1) 
  
  for (age in base_years){
     time_FR_NN[index] <- unlist(female %>% 
                               filter(AgeSection == age, Section == 0) %>% 
                               select(predict_rescale))
     time_FI_NN[index] <- unlist(female %>% 
                               filter(AgeSection == age, Section == 1) %>% 
                               select(predict_rescale))
    time_MR_NN[index] <- unlist(male %>% 
                               filter(AgeSection == age, Section == 0) %>% 
                               select(predict_rescale))
    time_MI_NN[index] <- unlist(male %>% 
                               filter(AgeSection == age, Section == 1) %>% 
                               select(predict_rescale))
    
    index <- index + 1
  }
  
femaleR_time <- unlist(female %>% filter(Section == 0) %>% 
               select(predict_rescale)) #times for females all ages 
femaleI_time <- unlist(female %>% filter(Section == 1) %>% 
               select(predict_rescale))
maleR_time <- unlist(female %>% filter(Section == 0) %>% 
               select(predict_rescale))
maleI_time <- unlist(female %>% filter(Section == 1) %>% 
               select(predict_rescale))

#factor27_F_NN = femaleNN/time_F_NN[1] #;
#factor27_M_NN = maleNN/time_M_NN[1] 
out$factor30_FR = femaleR_time/time_FR_NN[2]
out$factor30_FI = femaleI_time/time_FI_NN[2]
out$factor30_MR = maleR_time/time_MR_NN[2]
out$factor30_MI = maleI_time/time_MI_NN[2]#times divided by time at age 30 
#factor35_F = female/time_F[3] ; factor30_F = male/time_F[3]
return(out) 
}

set.seed(1)
factor30S_NN <- do(10)*boot_NN_Section(scaled_data = scaled, samplesize, ds_NN, testdata = scaled_testdataSection, rescaled_testdata = testdataSection)

factor30S_NN <- lapply(factor30S_NN, function(x){  
  as.data.frame(sapply(x,rbind))
  })
```


### Visuals 

```{r}
fr <- as.vector(factor30S_NN$factor30_FR) ; mr <- as.vector(factor30S_NN$factor30_MR)
fi <- as.vector(factor30S_NN$factor30_FI) ; mi <- as.vector(factor30S_NN$factor30_MI)
dfr <- as.data.frame(cbind( Age75, fr)) ; dmr <- as.data.frame(cbind( Age75, mr))
dfi <- as.data.frame(cbind( Age75, fi)) ; dmi <- as.data.frame(cbind( Age75, mi))


ggplot() + geom_point( data = dfr, aes(Age75, fr), color = "blue") +
  geom_point( data = dmr, aes(Age75, mr), color = "red") +
  geom_point( data = dfi, aes(Age75, fi), color = "green") +
  geom_point( data = dmi, aes(Age75, mi), color = "black")

```
